# Generated by Django 5.1.2 on 2025-04-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_system",
            "0004_remove_careappointment_user_careappointment_customer",
        ),
        ("personnel_management", "0001_initial"),
        ("schedule_system", "0002_schedule_calendar_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="配對時間"),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_system.careappointment",
                        verbose_name="客戶預約",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule_system.schedule",
                        verbose_name="員工排班",
                    ),
                ),
            ],
        ),
    ]
