# Generated by Django 5.1.2 on 2024-10-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
