# Generated by Django 5.1.2 on 2025-03-31 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_system", "0002_careappointment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careappointment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="careappointment",
            name="customer",
        ),
        migrations.AddField(
            model_name="careappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待處理"),
                    ("confirmed", "已確認"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=10,
                verbose_name="狀態",
            ),
        ),
        migrations.AddField(
            model_name="careappointment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="careappointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="careappointment",
            name="appointment_datetime",
            field=models.DateTimeField(verbose_name="預約時間"),
        ),
        migrations.AlterField(
            model_name="careappointment",
            name="care_location",
            field=models.CharField(max_length=255, verbose_name="預約地點"),
        ),
        migrations.AlterField(
            model_name="careappointment",
            name="special_requirements",
            field=models.TextField(blank=True, null=True, verbose_name="特別需求"),
        ),
    ]
