# Generated by Django 5.1.2 on 2025-04-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_system", "0003_remove_careappointment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careappointment",
            name="user",
        ),
        migrations.AddField(
            model_name="careappointment",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="careappointments",
                to="customer_system.customerprofile",
            ),
        ),
    ]
