# Generated by Django 5.1.2 on 2024-11-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="calendar_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
